### PR TITLE
Fellowship Cohort 1 gallery and individual pages populated

### LINKED ISSUE #278: FCAI: Add project list with short lay summaries to C1 and C2 fellowship pages

### LINKED ISSUE #343: Fellowship pages: create Cohort 1 gallery photos and statements

### LINKED ISSUE #349: Fellowship pages: link to archived versions of fellowship outputs (Cohort 1) to anticipate linkrot

### PR DESCRIPTION
**Pull request by alexandertdeng**
New layout and _includes pages for fellowships created

Photos uploaded, 1 per fellow as required
Social media and publication links populated per fellow

Link to fellowship booklet removed- content moved to fellow pages.

Currently fellow markdown files lives in /_team_member/fellowname.md

### CODE REVIEW

**Comment by hshuaib90** [comment]
Thanks Alex. Have added Bea as reviewer too. Will try to have a look asap

**Comment by dangerdika** [comment]
@alexandertdeng can you make a sub-folder for fellowships and put the fellow member pages and images there? im weary of this making the team_members folder for the CSC unusuable in a cohort or two, and i dont think their URLs should say csc/team_member/name for the fellows, it should be csc/fcai/cohort1/name or something like that. I'd also prefer if the structure of the fellows gallery was different than the CSC team one to avoid conflation of teams and members. Happy to lend a hand if you're not sure how to implement that!

**Comment by alexandertdeng** [comment]
> @alexandertdeng can you make a sub-folder for fellowships and put the fellow member pages and images there? im weary of this making the team_members folder for the CSC unusuable in a cohort or two, and i dont think their URLs should say csc/team_member/name for the fellows, it should be csc/fcai/cohort1/name or something like that. I'd also prefer if the structure of the fellows gallery was different than the CSC team one to avoid conflation of teams and members. Happy to lend a hand if you're not sure how to implement that!

Yes, that makes sense to have fellows in their own folder. I'm not sure how to implement that - where is the relationship between folders of markdown files and html pages to build specified?

**Comment by alexandertdeng** [comment]
> @alexandertdeng can you make a sub-folder for fellowships and put the fellow member pages and images there? im weary of this making the team_members folder for the CSC unusuable in a cohort or two, and i dont think their URLs should say csc/team_member/name for the fellows, it should be csc/fcai/cohort1/name or something like that. I'd also prefer if the structure of the fellows gallery was different than the CSC team one to avoid conflation of teams and members. Happy to lend a hand if you're not sure how to implement that!

Would making the photographs square instead of round be visually distinct enough between fellows and team members?

**Comment by alexandertdeng** [comment]
Thank you @AnilMistry for showing me the method on this.

**Comment by AnilMistry** [comment]
Resolves #343

**Review by AnilMistry — DISMISSED** [review]
Looks ok, only criticism is that each fellow page has the image and text starting without a space between content and subnav.

**Comment by alexandertdeng** [comment]
> Looks ok, only criticism is that each fellow page has the image and text starting without a space between content and subnav.

Thank you, great spot
I think this fixed now. 
This was caused by the fellow layout not being listed on _includes/head.html

**Review by hshuaib90 — APPROVED** [review]
Looks good to me

**Pull request merged**
