### PR TITLE
Interactive platform layout

### PR DESCRIPTION
**Pull request by Lucrezia-Cester**
included interactive carousel to verbalize platforms' purposes

### CODE REVIEW

**Comment by Lucrezia-Cester** [comment]
Hi @hshuaib90, @laurencejackson, @dangerdika, @AnilMistry, @lucy-funnell, @heyhaleema , following Haris' comments and presentation yesterday I thought I'd add a carousel to the platform page so that a new user can have a 'verbalised' preview onto what each platform is supposed to do. Tom and I also discussed adding a figure of a map that shows the links between various platforms which would be made with drawio. This figure would then be added after the carousel.

Do you agree on this new layout? Do you have any different suggestion on how this should look like?



Screenshot 2022-06-16 172558

**Comment by lucy-funnell** [comment]
Develop AI Applications diagram: what do you think about putting this in to a triangle shape? 
Reading from left to right (ML-> Dev->Op) seems link a process but not all the sub-steps when you read it this way make sense.
If ML was at the top of the triangle it would cover both Dev and Op

**Comment by dangerdika** [comment]
You need to change the phrasing there, we aren't technically working *on* CogStack, we only use it and I don't think we'll be developing it, it should say 'software platforms we are working with' - else it sounds like we're trying to take credit. Also XNAT should be alongside CogStack in this (it may be below, idk! apologies if it is!)

**Comment by Lucrezia-Cester** [comment]
landscape_horizontal
landscape_radial
Hi all, for the landscape page we were thinking about adding a 'map' to show how the platforms tie to each other to help people understand what each platform does. In this regard would you rather have a radial map (top) or a horizontal map (bottom)?

Also, here is what those images look like at a higher resolution 
CSC_radial_landscape
landscape_map_horizontal

**Comment by hshuaib90** [comment]
Ooo very interesting. I really like the radial idea. I think it might need some work to make it bigger and clearer but i really like how it accurately represents the information.

**Comment by Lucrezia-Cester** [comment]
Here is how the three compartments of the landscape page look like now. Let me know if you want to add anything
landscape page
.

**Comment by laurencejackson** [comment]
Looks good Lu, few suggestions (others feel free to comment)

- I think I would prefer the inner "lifecycle" ring to be a bit less detailed. I don't think things like hyperparameter tuning are really a part of the lifecycle, it would be part of training. The inner circles could be "Data preparation -> Training -> deployment -> monitoring" or we could go even further with stripping it back with just 3 like "Data -> model -> application"
- I think cogstack and xnat should be separate segments to indicate they are separate systems 
- several of the platforms we use are a bit fuzzy on the boundaries of their interaction with other platforms. e.g. mlops and xnat should have some overlap, and MLOps and AIDE.
- Could we have a sort of radial colour scheme to make the separation of layers clearer?

**Comment by Lucrezia-Cester** [comment]
Hi @laurencejackson, 

Landscape-1

.

**Comment by Lucrezia-Cester** [comment]
I added a link map to the radial map image so that if you click on the name of the platform in the image you are redirected directly to the platform page
Screenshot 2022-06-20 at 20 02 27
.

**Comment by lucy-funnell** [comment]
Oh wow!!! This looks amazing!

**Comment by tomaroberts** [comment]
Latest changes and appearance:

image

**Comment by tomaroberts** [comment]
Going to merge.

@Lucrezia-Cester, basically done but I will add a new Issue as a reminder that the interactive Wheel needs fixing.

**Pull request merged**
