### PR TITLE
450 add elise bio

### LINKED ISSUE #450: Add Elise Bio

### PR DESCRIPTION
**Pull request by ElisePather**

### CODE REVIEW

**Comment by dangerdika** [comment]
@ElisePather hey - the pic is oval instead of round, can you resize into a square one so it renders like the rest? Thank you! The rest loads well :)

**Review by dangerdika — CHANGES_REQUESTED** [review]
Pic needs new dimensions, should be square!

**Comment by ElisePather** [comment]
@dangerdika I've changed the pic to a square.

**Review by dangerdika — APPROVED** [review]
Looks great and loads great! Thank you! Approved and margining now

**Pull request merged**
