### PR TITLE
Adds favicons.

### LINKED ISSUE #6: Add favicon to site
We don't have a favicon! Every site should have one :)

Some instructions on how to do it with Jekyll: https://ptc-it.de/add-favicon-to-mm-jekyll-site/

### PR DESCRIPTION
**Pull request by heyhaleema**
This PR closes #6 and adds:

- Favicons to the assets/img directory
- Related HTML to head.html

### CODE REVIEW

**Review by tomaroberts — CHANGES_REQUESTED** [review]
Functionally working:

image

But, can you change the favicon image so the original aspect ratio of the letters is retained? At the moment it's stretched vertically.

**Comment by heyhaleema** [comment]
Thanks @tomaroberts, I've now regenerated the icons and added a few more. 

image

For most of the icons, I've kept the background as white apart from the following where I felt it was too stark or there was no option for a white background. In these cases, I used the colour hex code of the original "CSC" text, i.e. #3d89fe, but I can change these if you'd like.

- Windows Metro, i.e. Windows 8 and 10 users can pin the website on their desktop and it appears as a tile.
   image
- macOS Safari Touchbar
   image

**Comment by tomaroberts** [comment]
This looks sickkkkk, thanks.

I particularly like this:

image

Wonder if we should toy with using this more generally as CSC logo...

**Comment by heyhaleema** [comment]
Could do! I regenerated the icons with the blue background in case we wanted to go down that route but, for some reason, Safari seems to replace it with a white background in the tab itself (despite the icon having enough contrast and displaying correctly in the search bar):

image

**Pull request merged**
