### PR TITLE
I have added my details for the team page

### PR DESCRIPTION
**Pull request by Ksonar262**

### CODE REVIEW

**Review by dangerdika — CHANGES_REQUESTED** [review]
Hey @Ksonar262, can you just trim your picture a tiny bit? I can see a line on the right-hand side of the picture. Should disappear if you remove the frame around it

**Comment by Ksonar262** [comment]
Hi, Dika, thanks for your feedback, I have amended the photo.

**Review by dangerdika — CHANGES_REQUESTED** [review]
Fantastic! Image looks great now! Do you mind just changing in your bio the first sentence, it should say Clinical Scientific Computing rather than Clinical Sciences and Computing? Then I can merge :) Thanks Kathan!

**Review by dangerdika — APPROVED** [review]
LGTM! Thank you for your perseverence on this @Ksonar262!

**Pull request merged**
