### PR TITLE
Include twitter feed

### PR DESCRIPTION
**Pull request by Lucrezia-Cester**
I have added twitter feeds at the bottom of the homepage

### CODE REVIEW

**Comment by Lucrezia-Cester** [comment]
Hi @tomaroberts this is ready to be reviewed. As we discussed previously, I have changed the amount of tweets that can be seen at a given time.

**Comment by tomaroberts** [comment]
@Lucrezia-Cester 

image

The feed itself is working which is great, although do we want Haris' personal feed or a more general CSC one?

More importantly, we need to integrate the feed properly into the layout of the site. Looking at the Miro board, we were going to have it side-by-side with the Calendar. This can be done with Bootstrap CSS applied to divs, e.g. something approx like this using the [col class](https://getbootstrap.com/docs/4.0/layout/grid/):

```
<div class="col-3">
  calendar code
</div>
<div class="col-1">
  twitter feed code
</div>
```

Happy to discuss more if you want.

**Comment by Lucrezia-Cester** [comment]
Hi @tomaroberts, I have addressed your review. Ready to be reviewed again. Cheers.

**Comment by tomaroberts** [comment]
Hi Lu – thanks, the design is basically there, however by adding the code to `_includes/calendar.html` it means that the Twitter feed also appears on the dedicated Calendar page (http://127.0.0.1:4000/calendar.html)

I think what you want to do is:
- Create `_includes/twitter.html`, then put lines 25-27 in there.
- Adjust `_layouts/home.html` so that it is something like:

```
---
layout: default
---
{% include navheader.html %}
{% include about.html %}
{% include roadmap.html %}
<div 70%>
   {% include calendar.html %}
</div>
<div 30%>
   {% include twitter.html %}
</div>
```

You've also implemented inline styling to position the divs, but I think this is causing responsiveness issues and the Twitter feed to overlap with the block above:

image

I think using the Bootstrap classes will help fix this. I'd suggest implementing the fixes I proposed above and then we can think about how to correct the positioning.

**Comment by Lucrezia-Cester** [comment]
Thanks @tomaroberts, I hadn't noticed that we had a dedicated single calendar page. Changed the home layout. 
This is what it renders for me now that I have applied the changes.

Screenshot 2022-05-04 at 07 35 52

**Pull request merged**
