### PR TITLE
Add SOP section

### LINKED ISSUE #115: Add SOPs and Guides to the Handbook
Migrate the old (and new!) write ups of SOPs so they're accessible on the website

### PR DESCRIPTION
**Pull request by heyhaleema**
This PR closes #115 and adds SOPs for:
- CogStack (based on previous version of CSC website [here](https://github.com/GSTT-CSC/gstt-csc-old/blob/main/SOPs.md))
- National Opt-Out*
- QIPS (based on previous version of CSC website [here](https://github.com/GSTT-CSC/gstt-csc-old/blob/main/SOPs.md))
- XNAT (based on previous version of CSC website [here](https://github.com/GSTT-CSC/gstt-csc-old/blob/main/SOPs.md))

\* Based on section in XNAT repo [here](https://github.com/GSTT-CSC/XNAT/blob/main/docs/SOP-Data-Checking.md#pii). Ideally, we should be updating NDOO guidance in one location and have the other(s) reference this instead of duplicating.

### CODE REVIEW

**Comment by hshuaib90** [comment]
This is great Haleema. A couple of comments from me:
- interesting design, which is different to the other pages, where only the selected 'SOP' is rendered to screen. When you first navigate to it, it is empty. Is there placeholder text or a default selection that would fill that up?
- I think SOP is a misnomer for the documents that are listed there. Maybe we can use a general 'Guides' or something like that.

**Comment by heyhaleema** [comment]
> This is great Haleema. A couple of comments from me:
> 
> * interesting design, which is different to the other pages, where only the selected 'SOP' is rendered to screen. When you first navigate to it, it is empty. Is there placeholder text or a default selection that would fill that up?

@hshuaib90 I made some changes to how it was done, e.g. in comparison to the Handbook section, because I felt like it might (1) become too long to scroll through and (2) help users focus on the particular section they're reading. Having said that and on further review, it would also be good to have the scroll area be constricted to a portion of the screen, so I'll see if I can add this to this PR, too. 

For the placeholder text, how does this look? Or would you prefer this disappears once you click on to the other sections? At the moment, you're unable to go back to the "home" page, e.g. you can't get back to the blank SOP page without refreshing.

image
image


> * I think SOP is a misnomer for the documents that are listed there. Maybe we can use a general 'Guides' or something like that.

@dangerdika and I discussed this a bit in #115 about "Guides" vs. "SOP", but I think I'm starting to lean towards the former again...

**Comment by hshuaib90** [comment]
Thanks Haleema. I agree regarding the scrolling issue on the handbook, i think this is good solution (with some scrolling functionality restored).

In terms of filling whitespace with text, I meant the space to the right of the contents column rather than below the title. It looks like an odd empty space. I think the text itself is good, again I hesitate over the use of SOPs now that we have a QMS with ACTUAL SOPS 😄

**Comment by heyhaleema** [comment]
> Thanks Haleema. I agree regarding the scrolling issue on the handbook, i think this is good solution (with some scrolling functionality restored).
>
@hshuaib90 @dangerdika I spent some time looking at the scrolling, and I think we should raise a separate issue if we want this change to be applied to other pages, too.
 
> In terms of filling whitespace with text, I meant the space to the right of the contents column rather than below the title. It looks like an odd empty space. I think the text itself is good, again I hesitate over the use of SOPs now that we have a QMS with ACTUAL SOPS 😄

I've also now changed "SOP" to "Guides", and inserted that text into the space to the right of the contents, i.e. this should appear when you first navigate to the Guides page and before you select a specific section in the navbar.

image

@dangerdika If we're happy with separating the standardisation of how we enable scrolling through the Handbook, Resources, etc., and with the Guides page having this type of scrolling for now, then I think this PR is now ready for review.

**Review by hshuaib90 — APPROVED** [review]
LGTM

**Pull request merged**
