### PR TITLE
Kpi skill matrix

### PR DESCRIPTION
**Pull request by Lucrezia-Cester**
I have added a skills matrix at the bottom of the layout page

### CODE REVIEW

**Comment by tomaroberts** [comment]
This looks promising Lu. I think the grey table colour is a bit of a clash with the lighter theme around the rest of the site. Otherwise, we should decide as a group what we want to include in the table and then get everyone to decide their skillsets.

**Comment by Lucrezia-Cester** [comment]
Hi @tomaroberts, yes I agree, it clashes. It is now white.

**Comment by Lucrezia-Cester** [comment]
@tomaroberts Hi Tom, I applied the changes. Can this be merged?

**Comment by tomaroberts** [comment]
@Lucrezia-Cester 

Here's how it looks for me.

image

At the moment, it's kind of just floating below the team member pictures. Perhaps you could give it its own title and shaded background (#F8F9FA) a bit like how the sections on the homepage transition between Hero Image > Roadmap > Calendar. Does that make sense?

Also need to finalise what we want the table to actually contain – what skills, what people to put in each cell of the table, etc.

**Comment by Lucrezia-Cester** [comment]
Hi @tomaroberts I have added the greyish bk colour as you suggested. 

I will say, regarding the addition of each person's skills, I would suggest, the same way as it was done for the about us page, each person makes their own additions and for now we present the layout as it is, maybe at a workshop?

**Comment by Lucrezia-Cester** [comment]
@tomaroberts Hi Tom, I have changed the location where the Kpi matrix is rendered. This is now ready for review.

**Comment by Lucrezia-Cester** [comment]
Hi @tomaroberts, @heyhaleema, @laurencejackson, @hshuaib90, @dangerdika, @lucy-funnell, Tom and I were discussing today how we would like this kpi skill matrix to look like. I made it so that when a user needs help with a certain **skill** (or platform, model, etc., this is still to be filled in) they have a choice of people they can ask their questions too. Let me know if you would prefer this the other way around (people and their associated skills) or if you have any specific thoughts on what the kpi should look like. 
kpi skill matrix

**Comment by lucy-funnell** [comment]
I like the visual set up.
I wonder if there is a level between In Progress and Experts maybe something like beginner, or competent.

**Comment by dangerdika** [comment]
I really love this! Especially that someone who has a question can quickly find out who to contact!

**Comment by hshuaib90** [comment]
This is great. There are two things to think about:
- how does this link with the training record in the QMS? Ideally there is one source of truth. Even if one is an extension of the other.
- Naming of skills. It sounds like this is for external users, in which case we should think of this as them trying to access a service. I.e. Instead of 'XNAT' as a skill we might have "Accessing radiology images" or something like that, taking into account the 15 principle of good service design.

**Comment by Lucrezia-Cester** [comment]
Hi @hshuaib90, I am going to remove IBM and Answer. What other partners logos would you like to be added?

**Comment by hshuaib90** [comment]
@Lucrezia-Cester i think your comment is for a different issue

**Review by tomaroberts — APPROVED** [review]
Thanks Lu. Looks good. Can you raise a separate issue to ask everyone to canvas which sections of the table people want to be added to.

**Pull request merged**
