### PR TITLE
changes 'our work' to ''projects'

### PR DESCRIPTION
**Pull request by rs-sprout98**
renamed our work to projects and removed subnav bar from new 'projects' tab. Resources added as link to handbook. Kept instances of 'ourwork' in code as is mentioned many times. Hopefully should solve issue :)

### CODE REVIEW

**Comment by tomaroberts** [comment]
Hi @rs-sprout98 – thanks for this. It needs some changes. There has been a bit more discussion here: #84 

Can you:

1)

Change the Projects subnav to be like this:

image

2) 

Add RESOURCES as a fifth tab in the About Us subnav:

image


We can keep the Handbook entry you added – always good to have multiple routes through website pages.

**Review by tomaroberts — CHANGES_REQUESTED** [review]
See comment above^^

**Comment by tomaroberts** [comment]
Almost there @rs-sprout98. The front page navbar still says OUR WORK:

image

I recommend doing CTRL+SHIFT+F in PyCharm, then searching for "our work" or variations on that. You'll be able to see through the entire repo where the phrase is used.

Can you also update the code so that where it used to say "our_work", etc. it's replaced with "projects", e.g.: `ourwork.html` becomes `projects.html`. And any other similar instances.

Thanks!

**Comment by rs-sprout98** [comment]
@tomaroberts I'm getting some resistance trying to refactor the ourwork.html - It wants me to change files in the site folder. Am I allowed to touch the site folder for this?

**Comment by rs-sprout98** [comment]
Ignore previous comment, should be fine now - I did not touch anything in site

**Comment by tomaroberts** [comment]
> @tomaroberts I'm getting some resistance trying to refactor the ourwork.html - It wants me to change files in the site folder. Am I allowed to touch the site folder for this?

You don't need to edits files in the _site folder. When you run `bundle exec ... ` it builds the website into the _site folder and that's what you see on localhost.

**Review by tomaroberts — APPROVED** [review]
Looking good! Thanks @rs-sprout98. Will merge.

**Comment by tomaroberts** [comment]
Resolves #84

**Pull request merged**
