### PR TITLE
Update AIC004_IncidentalFindingPE_CT.md

### PR DESCRIPTION
**Pull request by simoambr**
project updates

### CODE REVIEW

**Comment by hshuaib90** [comment]
is the clinical lead correct?

**Review by dangerdika — CHANGES_REQUESTED** [review]
@simoambr  you only need the last </strike> (after 4. Retrospective evaluataion), or else you need to add <strike> to each line - it currently comes through broken for 3. and 4. Update that and that's that!

**Comment by dangerdika** [comment]
@simoambr that comment is meant to say you need the end strike tag only after 4., instead it took my html and applied it to the comment!

**Review by dangerdika — APPROVED** [review]

**Review by dangerdika — APPROVED** [review]

**Comment by dangerdika** [comment]
Excellent, thank you! Approved, merging

**Pull request merged**
