### PR TITLE
added MONAI to communities page

### PR DESCRIPTION
**Pull request by Lucrezia-Cester**

### CODE REVIEW

**Comment by dangerdika** [comment]
typo in first sentence, should say 'framework' instead of 'frameworks' but page renders well - fix and we'll merge! Thank you! @Lucrezia-Cester

**Review by dangerdika — CHANGES_REQUESTED** [review]
'frameworks' should say 'framework'

**Comment by Lucrezia-Cester** [comment]
Hi @dangerdika, I fixed the typo as you requested

**Comment by dangerdika** [comment]
@Lucrezia-Cester thank youuuuuuu

**Pull request merged**
