### PR TITLE
Hackathon planning kit

### LINKED ISSUE #152: Create a CSC hackathon planning kit
Please add your feedback regarding how the hackathon was run, how it was organised and how it should be done. The end result of this issue will be a practical planning kit that we can put on the website and follow for future hackathons.

### PR DESCRIPTION
**Pull request by dangerdika**
currently in draft form, still needs a checklist added

### CODE REVIEW

**Review by hshuaib90 — CHANGES_REQUESTED** [review]
Thanks Dika. This looks great. Couple of issues:
- Can you look at the formatting of the 'Other things to consider' section, it hasn't formatted correctly.
- Can you add the checklist to the bottom of this page or somewhere else as a markdown text/file so that it can also be tracked using git

**Comment by dangerdika** [comment]
@hshuaib90 checklist added to the bottom now - I agree its better this way. The other things to consider looked funky cause it went straight into a bullet list - amended now and looks less weird.

**Review by hshuaib90 — CHANGES_REQUESTED** [review]
Thanks Dika this looks great. One change requested though, can you avoid mixing HTML with the markdown please? Markdown supports checkboxes (https://www.w3schools.io/file/markdown-checkbox-github/) and different heading levels (https://www.w3schools.io/file/markdown-headings/) so there's no need to include HTML tags. Do you mind fixing those please then I can merge.

**Comment by dangerdika** [comment]
@hshuaib90 updated to consist of markdown-only, content not changed

**Review by hshuaib90 — APPROVED** [review]
Great!

**Pull request merged**
